/*
 * The site mark is a fixed formula, so there is no reason to ship all of KaTeX
 * to the browser to draw it. This renders it once at build time.
 *
 * Regenerate with:  npm run logo
 */
import katex from 'katex';

const html = katex.renderToString(String.raw`\overrightarrow{s}W`, {
  displayMode: true,
  throwOnError: true,
});

process.stdout.write(
  `/* Generated by scripts/render-logo.mjs - do not edit. Run \`npm run logo\` to update. */\n` +
    `export const LOGO_HTML = ${JSON.stringify(html)};\n`,
);
